# Generated by Django 4.0.5 on 2022-07-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('fac_num', models.AutoField(primary_key=True, serialize=False)),
                ('fac_name', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('spec_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('spec_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recruits',
            fields=[
                ('book_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('pad_nm', models.CharField(max_length=50)),
                ('lvl', models.IntegerField()),
                ('fac_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.faculty')),
                ('spec_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.speciality')),
            ],
        ),
        migrations.CreateModel(
            name='Mass',
            fields=[
                ('mass_date', models.DateField(primary_key=True, serialize=False)),
                ('mass_name', models.CharField(max_length=30)),
                ('priest', models.ManyToManyField(to='app2.recruits')),
            ],
        ),
    ]
