# Generated by Django 4.0.5 on 2022-07-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruits',
            old_name='fac_name',
            new_name='fac_num',
        ),
        migrations.RenameField(
            model_name='recruits',
            old_name='spec_name',
            new_name='spec_code',
        ),
    ]
