# Generated by Django 4.0.5 on 2022-08-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='sn',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='partners',
            name='partner',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='people',
            name='fio',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='people',
            name='tel',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='places',
            name='place',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='types',
            name='typ',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='vendor',
            field=models.CharField(max_length=20),
        ),
    ]
