# Generated by Django 4.0.5 on 2022-08-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_alter_equipment_name_alter_equipment_sn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='comment',
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='place',
            field=models.ForeignKey(on_delete=models.SET(1), to='app3.places'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='responsible',
            field=models.ForeignKey(on_delete=models.SET(1), to='app3.people'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='shipment',
            field=models.ForeignKey(on_delete=models.SET(1), to='app3.shipments'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.ForeignKey(on_delete=models.SET(1), to='app3.status'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='tech',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='typ',
            field=models.ForeignKey(on_delete=models.SET(1), to='app3.types'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='vendor',
            field=models.ForeignKey(on_delete=models.SET(1), to='app3.vendors'),
        ),
        migrations.AlterField(
            model_name='people',
            name='comment',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='people',
            name='partner',
            field=models.ForeignKey(on_delete=models.SET(1), to='app3.partners'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='comment',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='contact',
            field=models.ForeignKey(on_delete=models.SET(1), to='app3.people'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='partner',
            field=models.ForeignKey(on_delete=models.SET(1), to='app3.partners'),
        ),
    ]
