# Generated by Django 4.0.5 on 2022-08-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_alter_equipment_comment_alter_equipment_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipments',
            name='ship_id',
            field=models.CharField(default='Не определено', max_length=15),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='in_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='out_date',
            field=models.DateField(blank=True),
        ),
    ]
