# Generated by Django 4.0.5 on 2022-08-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0004_shipments_ship_id_alter_shipments_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='shipment',
            field=models.ForeignKey(blank=True, on_delete=models.SET(1), to='app3.shipments'),
        ),
    ]
